package com.example.friendsorganiser.Utilities;

public class Constants {
    public static final String KEY_DATABASE_USERS = "Users";
    public static final String KEY_DATABASE_CHATS = "Chats";
    public static final String KEY_DATABASE_APPOINTMENTS = "Appointments";
    public static final String KEY_DATABASE_NOTIFICATIONS = "Notifications";
    public static final String KEY_FIRESTORE_PROFILE_IMAGES = "ProfileImages";
    public static final String KEY_FIRESTORE_APPOINTMENTS_IMAGES = "AppointmentsImages";
    public static final String KEY_FIRESTORE_CHATS_IMAGES = "ChatsImages";
    public static final String KEY_NAME = "name";
    public static final String KEY_SURNAME = "surname";
    public static final String KEY_DATE_OF_BIRTH = "dateOfBirth";
    public static final String KEY_EMAIL = "email";
    public static final String KEY_PASSWORD = "password";
    public static final String KEY_PREFERENCE_NAME = "chatAppPreference";
    public static final String KEY_IS_SIGNED_IN = "isSignedIn";
    public static final String KEY_USER_ID = "userId";
    public static final String KEY_IMAGE = "image";
    public static final String KEY_FCM_TOKEN = "FCMToken";
    public static final String KEY_FRIENDS = "friends";
    public static final String KEY_ACCEPT_FRIENDSHIP = "accept";
    public static final String KEY_REJECT_FRIENDSHIP = "reject";
    public static final String KEY_RECENT_APPOINTMENTS = "recentAppointments";
    public static final String KEY_APPOINTMENT_TITLE = "title";
    public static final String KEY_APPOINTMENT_DATE = "date";
    public static final String KEY_APPOINTMENT_ADDRESS = "address";
    public static final String KEY_APPOINTMENT_ID = "appointmentId";
    public static final String KEY_APPOINTMENT_GEO_POINT = "geoPoint";
    public static final String KEY_APPOINTMENT_LATITUDE = "latitude";
    public static final String KEY_APPOINTMENT_LONGITUDE = "longitude";
    public static final String KEY_APPOINTMENT_PARTICIPANTS = "participants";
    public static final String KEY_FULL_ADDRESS = "display_name";
    public static final String KEY_SET_ADDRESS = "setAddress";
    public static final String KEY_SENDER_ID = "senderId";
    public static final String KEY_MESSAGE = "message";
    public static final String KEY_TIMESTAMP = "timestamp";
    public static final String KEY_CHAT_NAME = "chatName";
    public static final String KEY_CHAT_PARTICIPANTS = "participants";
    public static final String KEY_CHAT_ID = "chatId";
    public static final String KEY_MESSAGES = "messages";
    public static final String KEY_SENDER_FULL_NAME = "fullName";
    public static final String KEY_RECENT_CHATS = "recentChats";
    public static final String KEY_LAST_MESSAGE = "lastMessage";
    public static final int KEY_MESSAGE_FROM_ME = 1;
    public static final int KEY_MESSAGE_FROM_OTHERS = 2;
}
